# Generated by Django 4.1.7 on 2025-05-15 12:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import live_photo.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='相册名称')),
                ('date', models.DateField(blank=True, null=True, verbose_name='日期')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '相册',
                'verbose_name_plural': '相册',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='标签名称')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original', models.ImageField(upload_to=live_photo.models.gallery_photo_path, verbose_name='原图')),
                ('thumbnail', models.ImageField(upload_to=live_photo.models.gallery_thumbnail_path, verbose_name='缩略图')),
                ('metadata', models.JSONField(default=dict, verbose_name='元数据')),
                ('status', models.CharField(choices=[('visible', '显示'), ('hidden', '隐藏'), ('pending', '待补充')], default='visible', max_length=10, verbose_name='状态')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='live_photo.gallery', verbose_name='所属相册')),
                ('tags', models.ManyToManyField(blank=True, related_name='photos', to='live_photo.tag', verbose_name='标签')),
            ],
            options={
                'verbose_name': '照片',
                'verbose_name_plural': '照片',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_name', models.CharField(max_length=100, verbose_name='访问者姓名')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('user_agent', models.TextField(blank=True, verbose_name='用户代理')),
                ('accessed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='访问时间')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='live_photo.gallery', verbose_name='相册')),
            ],
            options={
                'verbose_name': '访问日志',
                'verbose_name_plural': '访问日志',
                'ordering': ['-accessed_at'],
            },
        ),
    ]
