# Generated by Django 4.1.7 on 2025-05-15 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('live_photo', '0002_alter_gallery_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='cover_photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cover_of_galleries', to='live_photo.photo', verbose_name='封面照片'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='日期'),
        ),
    ]
