# Generated by Django 4.2.20 on 2025-05-19 13:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_photo', '0003_gallery_cover_photo_alter_gallery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='name',
            field=models.CharField(help_text='相册名称（支持emoji表情）', max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(1, message='相册名称不能为空'), django.core.validators.MaxLengthValidator(100, message='相册名称不能超过100个字符')], verbose_name='相册名称'),
        ),
    ]
